#!/usr/bin/env python

import os
import sys
from datetime import datetime
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv

load_dotenv()

if len(sys.argv) != 2 or not sys.argv[1].isdigit():
    print("Usage: mk2folder [number]")
    sys.exit(1)

if not os.getenv("USER_AGENT"):
    print("[ERROR] Environment variable 'USER_AGENT' is not set.")
    sys.exit(1)

number = sys.argv[1]
url = f"https://www.acmicpc.net/problem/{number}"
headers = {"User-Agent": os.getenv("USER_AGENT")}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")
description = "\n".join(p.text.strip() for p in soup.select("#problem_description > *"))
input = "\n".join(p.text.strip() for p in soup.select("#problem_input > *"))
output = "\n".join(p.text.strip() for p in soup.select("#problem_output > *"))
samples = soup.select(".sampledata")

if not (description and input and output and samples):
    print("[ERROR] Couldn't fetch the data: {number}")
    sys.exit(1)

sample_strings = []

for index, sample in enumerate(samples):
    sequence = (index // 2) + 1
    if index % 2 == 0:
        sample_strings.append(f"\n## 예제 입력 {sequence}\n\n```\n{sample.text}\n```\n")
    else:
        sample_strings.append(f"\n## 예제 출력 {sequence}\n\n```\n{sample.text}\n```\n")

sample_strings = "".join(sample_strings)

markdown = f"""# {number}

[코딩테스트 연습 - {number}][1] 로 이동

## 문제

{description}

## 입력

{input}

## 출력

{output}
{sample_strings}
## 풀이

```python

```

[1]: {url}"""

# 디렉토리와 python 파일, README 생성
date = datetime.today().strftime("%Y-%m-%d")
os.makedirs(date, exist_ok=True)
os.makedirs(f"{date}/{number}", exist_ok=True)
with open(f"{date}/README.md", "a", encoding="utf-8") as file:
    pass
with open(f"{date}/{number}/{number}.py", "w") as file:
    pass
with open(f"{date}/{number}/README.md", "w", encoding="utf-8") as file:
    file.write(markdown)

# 완료 메시지 출력
print(f"Folder and structure created at {date}/{number}")
print(f"The python file created at: {date}/{number}/{number}.py")
print(f"The readme file created at: {date}/{number}/README.md")
